# Generated by Django 5.2.3 on 2025-07-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom_App', '0002_all_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Latest_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('description', models.TextField()),
            ],
        ),
    ]
