# Generated by Django 5.1.1 on 2025-07-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom_App', '0004_blog_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_product',
            name='price',
        ),
        migrations.AddField(
            model_name='blog_product',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
